version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ${CONTAINER_NAME}_app
    volumes:
      - ./laravel:/var/www
    depends_on:
      - db
  nginx:
    image: nginx
    container_name: ${CONTAINER_NAME}_nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./laravel:/var/www
      - ./docker/nginx/routing-task.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  db:
    image: mysql
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql_files:/var/lib/mysql
    container_name: ${CONTAINER_NAME}_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 0
